### ISSUE TITLE
WG & WS to lowercase

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-static#11]
A jeśli ma zostać uppercase, to trzeba dać znać Krzyśkowi.

**Comment by gkrajewski** [comment]
Tylko CDI-III ma funkcjonować w tych wszystkich parametrach URL jako `cdi-iii`, a nie samo `iii`. Chyba że coś mi się pomyliło ;)

**Comment by pikrol** [comment]
No chyba ciągle było wszędzie pisane "iii" i tak też jest w mailu od
Krzysztofa Soboty

pon., 15 lut 2021 o 22:36 gkrajewski <notifications@github.com> napisał(a):

**Comment by pikrol** [comment]
iii na pewno oznacza cdi3 (dyskusja mailowa w temacie 'Shiny na OVH')
