### ISSUE TITLE
Część demograficzna

### ISSUE THREAD

**Issue by pikrol** [pikrol/CDI-static#12]
Ustaliliśmy wczoraj, że wykorzystujemy parametr URL (form - wg albo ws) do sprawdzania poprawności wybrania daty urodzenia dziecka i moje pytanie: Jakie dokładnie ustalamy przedziały dla wg i ws oraz jaki minimalny i maksymalny możliwy wiek? 

Zakładam, że nie pozwalamy zatwierdzić części demograficznej, czyli ukończyć cdi jeśli wiek nie będzie wybrany. 

Podobnie z płcią - są 3 opcje: Kobieta, Mężczyzna, Inna. I też ma być sprawdzenie czy została wybrana, któraś z tych 3 opcji prawda?

@gkrajewski  @karolina-m

**Comment by gkrajewski** [comment]
Nie pozwalamy na nic, dopóki nie podadzą daty urodzenia i płci :)

- Płeć: "dziewczynka", "chłopiec", "inna" (w zależności od podanej płci właściwa tabela z normami; jeśli płeć inna, to normy unisex)

- Wiek (jeśli ja dobrze rozumiem to, co sami napisaliśmy w [tym pliku](https://docs.google.com/document/d/13hVsa1ECoXF1IN6izj85PkyuqRDhPkjGBonYrrFN8ac/edit?usp=sharing), ale dzwoniłem do @karolina-m, żeby się upewnić, więc chyba dobrze):

     - punkt odcięcia to 18 miesięcy, tzn. do wieku 18 miesięcy dostają wg, a od 19 miesięcy dostają ws (**uwaga**: to oznacza, że jak dziecko ma 18 miesięcy i 31 dni, to wciąż wg)
     - jeśli dziecko ma 36 miesięcy (na wszelki wypadek to może być _co najmniej_ 36), dostają cdi3 (**uwaga**: cdi3 jeszcze oczywiście nie ma, ale chyba apka powinna być gotowa na pojawienie się go)
