### ISSUE TITLE
Dokumentacja

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-static#17]
Obawiam się, że może być jednak niezbędny (a w każdym razie bardzo przydatny) jakiś opis akceptowanego formatu plików z treściami i konfiguracyjnych. Może być bardzo skrótowo i hasłowo: zakładamy, że targetem takiej dokumentacji będą ludzie nie tylko inteligentni, ale też obeznani z CDIami ;)

**Comment by pikrol** [comment]
Zrobiłem coś takiego:

https://docs.google.com/document/d/19KAue_EKB7bNr0zFZjQC0GCON1gJ2D1H7veNsMMtNtg/edit?usp=sharing

Można komentować i będę uzupełniał/modyfikował.

@karolina-m  @gkrajewski

**Comment by gkrajewski** [comment]
Świetnie! Ja na razie dopisałem parę wstępnych komentarzy, ale tak naprawdę to przetestuję tę instrukcję jutro, jak zacznę szykować brytyjską wersję. Ale już widzę, że bez niej bym błądził jak dziecko we mgle :)

**Comment by pikrol** [comment]
@gkrajewski
