### ISSUE TITLE
longText w (uni)Translations.csv

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-static#20]
Jest taka pozycja w uniTranslations.csv, ale niestety tekst tam jest wzięty z WG, a w WS jest trochę (ale w kluczowych sprawach) inny. Widzę dwie opcje:
1. przerabiamy (@pikrol, @karolina-m, @gkrajewski) ten tekst oraz te, które są w plikach translations.csv dla poszczególnych wersji (WG, WS), tak, żeby to miało sens;
2. @pikrol dorabia odpowiednie pole w plikach translations.csv, żeby ten tekst wprowadzający był tam, a nie w pliku "ogólnym".

Druga opcja byłaby lepsza, bo zachowywałaby większą zgodność z papierowym oryginałem.

**Comment by pikrol** [comment]
Ten tekst może być jak najbardziej w pliku translations.csv (czyli mogę być
różne dla różnych wersji). Uroiło mi się, że to wprowadzenie jest
identyczne dla obu inwentarzy.

pon., 22 lut 2021 o 13:00 gkrajewski <notifications@github.com> napisał(a):

**Comment by gkrajewski** [comment]
A jak (i w którym miejscu) go tam wsadzić? W pliku uniTranslations on jest na samej górze w drugiej linijce. Siedzę właśnie nad tymi instrukcjami, to bym to zrobił i dał pull request.

**Comment by pikrol** [comment]
Skopiować wiersz z uniTranslations do translations. Najlepiej przed
pierwszym itemem typu 'understanding'.

pon., 22 lut 2021 o 13:46 gkrajewski <notifications@github.com> napisał(a):
