### ISSUE TITLE
Demo/start a dalsze części

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-static#23]
Po zatwierdzeniu płci i wieku nie można do nich wrócić, **ale** bez zatwierdzenia można latać po kolejnych częściach. To trochę niespójne?

**Comment by pikrol** [comment]
Czyli wszystkie części powinny być początkowo niedostępne? (oprócz start)

Uznałem, że i tak się nie ukończy inwentarza bez zatwierdzenia części
demograficznej, więc jest bez znaczenia czy można latać czy nie.

wt., 23 lut 2021 o 00:57 gkrajewski <notifications@github.com> napisał(a):

**Comment by gkrajewski** [comment]
Wydaje mi się, że to by wyglądało lepiej, ale myślę, że to feature for
future może być ;)

**Comment by pikrol** [comment]
Zrobione. To było szybkie.
