### ISSUE TITLE
Polskie literki

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-static#28]
U GK polskie literki są blade, a u KM większe od reszty.

**Comment by pikrol** [comment]
@gkrajewski  @karolina-m  Mam hipotezę, że to zależy od używanej przeglądarki. Czy mogą Państwo się pochwalić jakiej używają?

**Comment by karolina-m** [comment]
Ja zazwyczaj używam Chrome (o dziwo, polskie znaki teraz wyglądają ok - tak mi się wydaje)
![image](https://user-images.githubusercontent.com/7211151/109282324-ac000800-781d-11eb-8379-85242286ee70.png)

A tu Firefox (wyglądają tak samo):
![image](https://user-images.githubusercontent.com/7211151/109282511-e7023b80-781d-11eb-8f33-018d5f51e5e5.png)

**Comment by pikrol** [comment]
To ciekawe, bo nic jeszcze nie zmieniałem.

**Comment by gkrajewski** [comment]
Ja na co dzień Safari (sprawdziłem, wciąż blade), a teraz odpaliłem Chroma
i wszystko ślicznie. Ale to mnie nie dziwi: to chyba normalne, że takie
czcionkowe problemy są przeglądarkozależne. A właściwie firmozależne. Np. w
arkuszu xlsx (Mircosoft) czcionka Calibri (chyba propriety Microsoftu) w
Safari (Apple) w Google Sheets (Google) też ma takie kulfony:
[image: image.png]

**Comment by karolina-m** [comment]
To ja już nie wiem - ale wydaje mi się, że polskie znaki teraz są ładniejsze niż były kilka dni temu... w tej samej przeglądarce. Może to jest "in the eye of the beholder"... ;)

**Comment by pikrol** [comment]
Wiem już jak zaradzić. Będzie zmienione w następnej wersji.
