### ISSUE TITLE
Sprawdzanie wieku

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-static#29]
Jeżeli jest plik z siatką centylową, to bierzemy z niego zakres wiekowy i sprawdzamy na tej podstawie, czy wpisana data urodzenia jest właściwa. Jeżeli nie ma siatki centylowej, to nie sprawdzamy daty urodzenia.

**Comment by pikrol** [comment]
Chcę się tylko upewnić. Normy, które mam dotyczą tylko wersji polskiej tak? A co z innymi wersjami językowymi czy dla nich też planujemy dawanie feedbacku w oparciu o normy?

**Comment by gkrajewski** [comment]
Normy w plikach ode mnie dotyczą tylko polskich CDIów. Na razie nie
dorzucamy plików z normami do innych wersji językowych, czyli mechanizm
musi być "odporny" na brak norm. Nie zamierzamy pingać bazy SW w oparciu o
normy brytyjskie lub norweskie, czyli po wypełnieniu brytyjskiego lub
norweskiego CDIa możemy po prostu przesyłać zawsze TRUE.
