### ISSUE TITLE
Sidebar po prawej

### ISSUE THREAD

**Issue by pikrol** [pikrol/CDI-static#30]
Nawiązując do maila z wątku 'Norwegian CDI WG and WS' mam pytanie: zmieniamy sidebar na prawo? Ja się zgadzam z tym, że to nieintuicyjne teraz.  Wtedy na telefonie sidebar będzie pod spodem, a nie u góry. Wiem, że @karolina-m o tym już pisała, ale wtedy to chyba zignorowałem ze strachu, że to kupa roboty. Sprawdziłem teraz i to jest dziecinnie proste i taka zmiana zajmuje 3 sekundy. Można nawet regulować szerokość sidebara w stosunku do main panelu! (tego gdzie są pytania) Więc jak macie Państwo w głowie jakąś złotą proporcję to możecie podać :)

**Comment by karolina-m** [comment]
Super, jak to nie problem, to rzeczywiście bardziej intuicyjnie będzie mieć sidebar po prawej (w wersji na komputer) i na dole (w wersji na telefon). Ale złotej proporcji w głowie nie mam :D

**Comment by gkrajewski** [comment]
Też się zgadzam, że prawo i dół są bardziej intuicyjnie (choć to lewo
mi nie przeszkadzało...).
