### ISSUE TITLE
Czasem środek listy, a czasem dół

### ISSUE THREAD

**Issue by pikrol** [pikrol/CDI-static#32]
"3. Kiedy przechodziłam między listami słów w zakładce wyrazy, czasem po przejściu byłam "przerzucona" na środek listy, a czasem bez zmian zostawałam na dole. Byłoby mi chyba trochę wygodniej gdybym zawsze startowała od początku, ewentualnie od dołu, żeby nie pominąć jakiś pozycji, bo na telefonie czasem trzeba trochę poprzewijać w dół, ale może to kwestia mojej orientacji :) Być może to też kwestia mojego telefonu (jestem na iOS i otwierałam kwestionariusz w Safari)" ~Magdalena Krzysztofiak

**Comment by gkrajewski** [comment]
Zawahałem się, czy nie otagować tego jaku future. A może wprowadzić tag near-future ;) Zasadniczo trzeba chyba rozpączkowującą listę issues zacząć jakoś priorytetyzować. Widziałbym co najmniej trzy grupy: kwestie kluczowe do ogarnięcia przed deplojmentem, kwestie drobne do poprawienia po deplojowaniu, kwestie na przyszłość. @karolina-m jak to widzisz?

**Comment by pikrol** [comment]
To akurat było szybkie.
