### ISSUE TITLE
Dorobić pytanie o to kto wypełnia

### ISSUE THREAD

**Issue by pikrol** [pikrol/CDI-static#39]
Mama
Tata
Babcia
Dziadek
Niania
Nauczyciel
Inne (napisz kim jesteś dla dziecka)

**Comment by gkrajewski** [comment]
Jeszcze nie oglądałem, jak to wygląda w rzeczywistości, ale czy odpowiedzi mogłyby być takie (małymi literami):
```
mama
tata
babcia
dziadek
niania
nauczyciel(-ka)
inna odpowiedź (napisz, kim jesteś dla dziecka):
```
Chociaż to pewnie w pliku z translacjami sam mógłbym zmienić?

**Comment by karolina-m** [comment]
dla mnie ok, dodałam już -ka (do nauczyciela) w apce SW.

**Comment by gkrajewski** [comment]
Ja wolę małe, ale najważniejsze, żeby było spójnie z innymi pytaniami.

**Comment by pikrol** [comment]
No dobrze, będą małe.

@karolina-m  trzeba dodać to samo do norweskiego, przygotowałem już na to miejsce w uniTranslations (text_type fillerLabel i fillers)
