### ISSUE TITLE
Parametry URL

### ISSUE THREAD

**Issue by pikrol** [pikrol/CDI-static#43]
- [x] Dodanie komunikatu o błędnych parametrach
- [x] Parametry URL case invariant?

**Comment by gkrajewski** [comment]
O co dokładnie chodzi z tymi błędnymi parametrami? Parametry będą przecież częścią generowanego przez apkę SW adresu url, więc z definicji powinny być bezbłędne. Chyba że zakładamy, że ktoś z palca wpisze adres. Ja bym wtedy najchętniej widział przekierowanie takiej osoby na stronę główną (która btw przekierowuje na stronę https://multilada.pl/projekty/cdi/: to takie moje tymczasowe rozwiązanie, zanim rozwiniemy stronę cdi.multilada.pl).

**Comment by pikrol** [comment]
No to takie marzenie Krzysztofa Soboty, by nie trzeba było się martwić czy
jest wg WG wG czy Wg. Ale chyba też nie jestem przekonany do robienia tego.
Właśnie się zastanawiam czy przekierowywać na tą stronę, czy wyświetlić po
prostu komunikat, że zły adres URL w takiej sytuacji?

śr., 17 mar 2021 o 22:33 gkrajewski ***@***.***> napisał(a):

**Comment by gkrajewski** [comment]
Krzysiek ma pewnie rację, że eleganciej jest case invariant. To by zresztą ułatwiało zadanie osobom, które chciałyby jednak z palca przepisać url z telefonu na komputerze. Więc jeśli można to szybko dodać, to jestem na tak!

Co do komunikatu, to może rzeczywiście lepiej czytelny i treściwy komunikat niż nieoczekiwane (z punktu widzenia rodzica, wstukującego url) przekierowanie?
