### ISSUE TITLE
Zaimki osobowe w pl-ws

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-static#46]
Ja już wcześniej o tym myślałem, ale wydawało mi się, że do tego będzie można wrócić na etapie przetwarzania zebranych danych. Natomiast dzisiaj uzmysłowiłem sobie, że my przecież liczymy wynik online i odnosimy go do norm, więc musimy to jednak załatwić na etapie zbierania danych.

W Słowach i Zdaniach zaimki osobowe liczone są **raz** niezależnie od tego, ile i które formy przypadkowe są zaznaczone, jak na załączonym obrazku (np. ja=mnie=mi). To oznacza, że musimy mieć **jedną** pozycję na każdy zaimek ("ja (mnie, mi" itd.). Dzierżawcze (mój, twój itd.) oraz się i sobie pozostają bez zmian, oddzielnie.

![image](https://user-images.githubusercontent.com/57642567/111542841-89a14080-8772-11eb-9a38-3481ff9c1609.png)

**Comment by pikrol** [comment]
Czyli to trzeba zmienić po prostu tylko w plikach wsadowych tak?
np. zamiast 3 pozycji ja, mnie, mi - zrobić jedną ja/mnie/mi ?

śr., 17 mar 2021 o 22:54 gkrajewski ***@***.***> napisał(a):

**Comment by gkrajewski** [comment]
Dokładnie!
`ja (mnie, mi)` albo `ja/mnie/mi`. Nie pamiętam, która wersja byłaby spójna interpunkcyjnie z resztą, ale chyba ta druga?
