### ISSUE TITLE
Obligatoryjne i warunkowe części kwestionariusza

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-static#5]
- [x] Każda część kwestionariusza musi się kończyć przyciskiem potwierdzającym jej wypełnienie. Wciśnięcie tego przycisku odhacza tę część tam, gdzie się nawiguje między częściami. Dopiero odhaczenie wszystkich obligatoryjnych części uaktywnia przycisk kończący całość.
- [x] Mogą być części warunkowe, które uaktywniają się dopiero po uzyskaniu określonego wyniku w innej części (NB trzeba tę inną część skończyć przyciskiem: patrz punkt wyżej). Taka warunkowość powinna być określona w pliku wsadowym.

**Comment by karolina-m** [comment]
I zgodziliśmy się żeby między ekranami w danej podkategorii był przycisk "dalej" + autozapisywanie; a na końcu podkategorii przycisk "zapisz"

**Comment by pikrol** [comment]
Zrobione. Zapraszam do testowania (narazie tylko IRMiKa SiG z niekompletną listą itemów, IRMiK SiZ powinien działać po przygotowaniu plików wsadowych tak samo). Link jest w pliku README.txt

**Comment by karolina-m** [comment]
Super jest! Mam propozycje tylko kilku drobnych zmian:
1) przycisk "zapisz"/"dalej" jednak powinien być po prawej stronie ekranu (tak chyba będzie bardziej intuicyjnie)
2) trochę mi się rozjeżdżają "R" i "M" w "Lista wyrazów" - tzn. nie są w jednej kolumnie. wrzucam screen poniżej:
![image](https://user-images.githubusercontent.com/7211151/98099260-9f7f2a80-1e8f-11eb-8fa3-3694e372e2c6.png)
3) odpowiedzi "jeszcze nie", "często" i "czasem" w "Łączenie wyrazów" są jakoś tak nieładnie ustawione ;) nie wiem na ile da się to edytować (tak jak te "R" i "M" powyżej), ale może mogą być pod sobą (w jednej kolumnie)?
![image](https://user-images.githubusercontent.com/7211151/98099557-03a1ee80-1e90-11eb-961e-fd85735f71e8.png)
4) Przyda nam się jeszcze ekran lub informacja tekstowa gdzieś o tym czym jest CDI (tak jak w papierowej wersji) - treść instrukcji pewnie będzie w tych plikach wsadowych?

**Comment by pikrol** [comment]
Ad. 1. Pewnie dałoby się to zrobić, chociaż może to wymagać trochę pracy. Wtedy w rozdzielczości telefonowej to menu z dalej/zapisz byłoby pod spodem głównej zawartości. W tej chwili to menu jest po lewej, bo chciałem by było analogicznie do przyszłego adaptatywnego CDI, w którym, jeśli zostaję przy pakiecie mirtCAT, właśnie tak będzie (i to raczej nie do zmiany) wyglądał interfejs. Może tu poczekamy czy podobne wrażenia o intuicyjności będzie miał @gkrajewski i ewentualni inni testerzy.

Ad. 2. Zobaczymy jak będzie to wyglądać po zmianie na checkboxy (jeśli taka zmiana będzie) ale w razie czego myślę, że to łatwo da się poprawić.

Ad. 3. Ok, popracuję nad tym.

Ad. 4. Założyłem, że ta informacja będzie sobie wisieć na stronie (czyli będzie np. nad tym inwentarzem), tak by w trakcie ładowania się apki Shiny (co tam pewnie z 3 sekundy potrwa) było już coś do czytania. Także z tym może poczekamy na wyklarowanie się wizji tej strony.

**Comment by pikrol** [comment]
Aha, jeszcze ważna rzecz: można testować także jak to wszystko wygląda na telefonie oraz w rozdzielczości większej niż ta na której testowała @karolina-m (czyli chyba laptop z małym ekranem/tablet?). Można po prostu zmniejszać/rozszerzać okno przeglądarki i patrzeć jak się te wszystkie elementy przestawiają i układają.

**Comment by karolina-m** [comment]
> Ad. 1. Pewnie dałoby się to zrobić, chociaż może to wymagać trochę pracy. Wtedy w rozdzielczości telefonowej to menu z dalej/zapisz byłoby pod spodem głównej zawartości. W tej chwili to menu jest po lewej, bo chciałem by było analogicznie do przyszłego adaptatywnego CDI, w którym, jeśli zostaję przy pakiecie mirtCAT, właśnie tak będzie (i to raczej nie do zmiany) wyglądał interfejs. Może tu poczekamy czy podobne wrażenia o intuicyjności będzie miał @gkrajewski i ewentualni inni testerzy.
ok!

> Ad. 2. Zobaczymy jak będzie to wyglądać po zmianie na checkboxy (jeśli taka zmiana będzie) ale w razie czego myślę, że to łatwo da się poprawić.
> 
> Ad. 3. Ok, popracuję nad tym.
> 
> Ad. 4. Założyłem, że ta informacja będzie sobie wisieć na stronie (czyli będzie np. nad tym inwentarzem), tak by w trakcie ładowania się apki Shiny (co tam pewnie z 3 sekundy potrwa) było już coś do czytania. Także z tym może poczekamy na wyklarowanie się wizji tej strony.
Ok, brzmi sensownie, do rozważenia przy późniejszym testowaniu.

**Comment by gkrajewski** [comment]
Otwieram na nowo to issue, bo chyba właśnie teraz musimy podjąć decyzję odnośnie do pktu 4 powyżej: co wieszamy na stronie w wordpressie, a co wkładamy w instrukcje do pliku wsadowego. Zasadniczo chyba jak najmniej chcemy wieszać (teraz) na stronie, bo strona nie będzie miała (przynajmniej na razie) oddzielnych wersji językowych, a instrukcje muszą pojawić się w danym języku? @karolina-m

**Comment by gkrajewski** [comment]
Ustaliliśmy, że na stronie zasadniczo nic nie będzie poza włochatym misiem i ewentualnie pabiqiem: wszystko siedzi w plikach z treściami.
