### ISSUE TITLE
Kilka uruchomień

### ISSUE THREAD

**Issue by pikrol** [pikrol/CDI-static#51]
"Ja bym na razie oczywiście dodał to, co piszecie wyżej
("odśwież, chyba że zacząłeś na innym urządzeniu"). Oprócz tego
dodałbym w instrukcji -- tam, gdzie piszemy, że można kontynuować na
innym urządzeniu -- wyjaśnienie/ostrzeżenie, że skorzystanie z linka
na innym urządzeniu powoduje zamknięcie kwestionariusza na tym, na
którym jest obecnie otwarty (i wyświetlenie komunikatu o błędzie), ale
że odpowiedzi (te zatwierdzone przyciskiem, prawda?) pozostają
zachowane." ~GK

**Comment by pikrol** [comment]
@gkrajewski a może po prostu do tekstu 

> Zakończenie inwentarza będzie możliwe dopiero po zatwierdzeniu wszystkich części. W każdej chwili można przerwać wypełnianie, co nie spowoduje utraty dotychczasowych odpowiedzi. Żeby wrócić do wypełniania (np. na innym urządzeniu), należy użyć dokładnie tego samego linku.

 dołożyć krótkie zdanie _Inwentarz może być otwarty tylko raz w danym momencie._ ? Już bez pisania co to powoduje jak się otworzy gdzie indziej. Bo to trochę źle wygląda jak ten ważny tekst pisany grubą czcionką jest taki długi - prawie dłuższy niż ten ze standardową czcionką.

I jeszcze do tego komunikatu o błędzie - trochę nie przekonuje mnie pisanie "Odśwież, chyba że zacząłeś na innym urządzeniu". Mnie taki komunikat jakoś stresuje, a przecież jak się odświeży pomimo, że się otworzyło gdzie indziej to nic takiego się nie stanie.

**Comment by gkrajewski** [comment]
Słusznie. To może po prostu do ostatniego zdania dodać na końcu nawias:
"(inwentarz nie może być wypełniany na kilku urządzeniach na raz)". Albo:
"(inwentarz nie powinien być wypełniany na kilku urządzeniach na raz)". Albo:
"(inwentarz nie może być otwarty na kilku urządzeniach na raz)". Albo:
"(inwentarz nie powinien być otwarty na kilku urządzeniach na raz)".

Co by najlepiej pasowało i brzmiało?

**Comment by pikrol** [comment]
Dlaczego nawias? Ja jestem za opcją trzecią od góry, bo chyba nie chodzi tu o powinności, ale o to co można. I chodzi o samo otwieranie, a nie wypełnianie.

**Comment by gkrajewski** [comment]
No to trzecia opcja. Jeżeli Pan woli, może być w formie dodatkowego
oddzielnego zdania, zamiast w nawiasie przy poprzednim :)
