### ISSUE TITLE
Dodanie parametru language do SW call

### ISSUE THREAD

**Issue by krzysiekkrk** [pikrol/CDI-static#57]
Zorientowałem się, że po ostatnich zmianach po stronie SW potrzebne będzie przekazanie wartości języka, dla którego wykonywany był CDI (tj. cieżko po stronie aplikacji jednoznacznie określić język ostatnio wykonanego CDI, a po stronie Shiny to powinno być proste przypisanie, czyli:

`
 mutation{
            upsertCdi(input:{
              token:\"", idToken, "\",
              cdi:{
                done:", done, ",
                cdiTypeId:\"", form, "\",
                childHash:\"", idx, "\",
                language:\"",lang,"\",
                score: ", score, "}}
                ){
                cdi{
                  pk,
                  cdiTypeId,
                  childHash,
                  score
                }
            }
        }
`
dodajemy zatem parametr "language" z GET. Ja to już później sparsuje po swojej stronie.

**Comment by pikrol** [comment]
Ok, zrobiłem to. Pierwszy call (po rozpoczęciu) przebiega ok, a przy drugim dostaję taki błąd "Warning: Error in .jnew: java.lang.NoClassDefFoundError: javax/activation/DataSource". Mam ten błąd tylko na jak testuję na darmowym hostingu shinyapps.io, jak testuję lokalnie to go nie ma.

**Comment by krzysiekkrk** [comment]
To raczej warning i jest związany z callem z poziomu RJava. Nie wiem na co dokładnie ma to wpływ.

**Comment by krzysiekkrk** [comment]
`
Warning: Error in : EmailException (Java): Sending the email to the following server failed : smtp.gmail.com:465
org.apache.commons.mail.EmailException: Sending the email to the following server failed : smtp.gmail.com:465
        at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1410)
        at org.apache.commons.mail.Email.send(Email.java:1437)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at RJavaTools.invokeMethod(RJavaTools.java:386)
Caused by: javax.mail.AuthenticationFailedException: 534-5.7.14
`
Nie zmieniana była czasem konfiguracja gmaila? Ten błąd zdaje się blokuje też zapis do aplikacji.

**Comment by krzysiekkrk** [comment]
https://github.com/datawookie/emayili/issues/49

**Comment by krzysiekkrk** [comment]
Zapis działa (język itd.), ale na problem z mailem proszę zerknąć. Ja przełączyłem się na swoje testowe konto i jest ok, ale na koncie używanym w CDI ten problem nadal będzie występował. Rozwiązanie z linku powyżej powinno załatwić sprawę.

**Comment by pikrol** [comment]
Tak, google przysłało maila, że zablokowało jakieś nieznane próby połączenia się z soboty wieczór.
Powinno teraz już działać

**Comment by pikrol** [comment]
Widzę, że na shinyapps.io dalej mam ten sam problem z wysłaniem maila, więc na OVH pewnie też może ciągle nie działać. Kombinuję jeszcze.

**Comment by krzysiekkrk** [comment]
Jednak działa. Proszę zerknąć na:
"This was it! Nice catch! I followed the bullet "If the tips above didn't help, visit https://www.google.com/accounts/DisplayUnlockCaptcha and follow the steps on the page." By using that page, I got the message "Account access enabled. Please try signing in to your Google account again from your new device or application.", then tried re-deploying the app, and everything worked, both within the Shiny app and the code placed outside the app (just run on the server)."
Z tego co wyczytałem to co jakiś czas trzeba powtórzyć proces (google resetuje to ustawienie co pewną liczbę dni).

**Comment by pikrol** [comment]
A czy robił Pan coś jeszcze tam? Bo ja próbowałem z tym DisplayUnlockCaptcha ale nie wystarczało. Do czego były potrzebne te kody SMS?

I co do tego powtarzania procesu - czy dotyczy to apek już zdeployowanych? Tzn. czy nie jest tak, że jak apka jest już zdeployowana to jak działa to będzie działać, tylko ewentualnie przy powtórnym deployowaniu trzeba będzie to znowu uwierzytelnić?

Ogólnie rozumiem, że na ten moment apka jest już zdeployowana i moglibyśmy testować?

**Comment by krzysiekkrk** [comment]
A czy robił Pan coś jeszcze tam? Bo ja próbowałem z tym
DisplayUnlockCaptcha ale nie wystarczało. Do czego były potrzebne te kody
SMS?
Nie, sms potrzebny był tylko do tego, żebym mógł coś skonfigurować na
koncie gmail. Nie robiłem tam nic poza DisplayUnlockCaptcha.

I co do tego powtarzania procesu - czy dotyczy to apek już zdeployowanych?
Tzn. czy nie jest tak, że jak apka jest już zdeployowana to jak działa to
będzie działać, tylko ewentualnie przy powtórnym deployowaniu trzeba będzie
to znowu uwierzytelnić?
Nie, raczej chodzi o sam czas. Z tego co wyczytałem, to Google resetuje
ustawienia dla konta email, a nie dla aplikacji jako takiej.

Ogólnie rozumiem, że na ten moment apka jest już zdeployowana i moglibyśmy
testować?
Tak, aplikacja jest zdeployowana.
