### ISSUE TITLE
UK CDI W&S

### ISSUE THREAD

**Issue by gkrajewski** [pikrol/CDI-static#6]
Katie twierdzi, że pozycji do W&S jest za dużo i trzeba wyselekcjonować na podstawie jej danych pilotażowych, ale według mnie te dane są słabe (w sensie N), więc może puścić jednak całość (698)? @karolina-m, do przedyskutowania chyba.

**Comment by karolina-m** [comment]
Z jednej strony: (1) tam było N=60 więc rzeczywiście niewiele. No i (2) polski CDI-II też jest długi (600+), więc może chociażby dla równowagi użyć pełnej listy itemów CDI W&S ang? A z drugiej strony ja mam w minutkach z kick-offu zapisane, że "the pilot version is certified by MacArthur Base CDI Adv Board" - czy to nas jakoś nie zobowiązuje?

**Comment by gkrajewski** [comment]
Pójdą wszystkie.
