### ISSUE TITLE
Sekcja lista wyrazów - radio buttons

### ISSUE THREAD

**Issue by pikrol** [pikrol/CDI-static#7]
Przyciski wykorzystane w sekcji lista wyrazów nie pozwalają się odznaczać. Czyli po zaznaczeniu "rozumie" albo "mówi" musi już zostać któraś z tych opcji. Nie da się zrobić tak by kliknięcie na "rozumie", w sytuacji gdy opcja ta jest już zaznaczona, spowodowało jej odznaczenie.

Jeśli to problem, a podejrzewam, że tak to widzę takie rozwiązania:

- Zmienienie radio buttons na checkboxy znane z innych części (tylko wtedy można zaznaczać i rozumie i mówi naraz, ale to chyba nie problem, bo gdzieś chyba czytałem, że rodzice i tak to robią w papierowej wersji i interpretuje się to wtedy po prostu jako "mówi")??
- Kliknięcie np. na tekst ("gę gę" itd.) spowoduje zresetowanie przycisku, czyli brak zaznaczenia. (ale to chyba nie do końca intuicyjne).
- Dodanie przycisku "resetuj wszystko", który zresetuje zaznaczenia z danej strony (ale to oznacza, że pomyłkowe zaznaczenie jednej opcji, powoduje konieczność zaznaczania wszystkiego jeszcze raz).
- Rozwiązanie najszybsze: Dodanie trzeciej opcji - "nie rozumie, nie mówi" (ale czy wtedy powinna być ona zaznaczona domyślnie? i czy to nie jest zbyt duża ingerencja w kwestionariusz?)

**Comment by karolina-m** [comment]
Jest to problem, ale fajnie że zaproponował Pan od razu kilka rozwiązań! Ja jestem za opcją 1 (checkboxy) - wydaje się być najbardziej intuicyjna i nie ingerująca w kwestionariusz. Co na to @gkrajewski?

**Comment by gkrajewski** [comment]
Ja też jestem za opcją pierwszą. Podział na rozumienie i mówienie to zmora (nie jedyna) CDI. W papierowej wersji są jednak oddzielne checkboxy (choć instrukcja SiG *sugeruje*, żeby zaznaczać albo jeden, albo drugi, albo żaden) i tego powinniśmy się trzymać. Natomiast na etapie zliczania wyników tam, gdzie jest zaznaczone M, zaznaczać R.

Inna kwestia jest taka, że podział na R i M istnieje tylko w SiG. W SiZ (i docelowo w CDI-III) jest tylko jedna kratka do odhaczenia.
