### ISSUE TITLE
Podsumowanie

### ISSUE THREAD

**Issue by pikrol** [pikrol/CDI-static#8]
Podsumowanie uaktywnia się obecnie automatycznie po zapisaniu wszystkich obligatoryjnych części. Zakładam, że to też spowoduje automatycznie przesłanie wyników, czy tak? (bo @gkrajewski pisał w #2 o guziku zamykającym całość, ale czy to konieczne? bo to zawsze jakiś dodatkowy wysiłek dla badanych, a zatwierdzenie wszystkich obligatoryjnych części jest chyba tożsame z zatwierdzeniem całego kwestionariusza, bo i tak już nie ma możliwości niczego zmieniać)

I tutaj zastanawiam się też co powinno być w podsumowaniu, czy tylko "dziękujemy za wypełnienie", czy dajemy też jakieś zbiorcze podsumowanie, a jeśli tak to jak powinno ono wyglądać?

**Comment by karolina-m** [comment]
Najbardziej odwzorowującym kontekst papierowego kwestionariusza będzie "dziękujemy za wypełnienie". Zresztą, używamy CDI-ów nie do celów diagnostycznych, a badawczych, i wydaje mi się, że w takich wypadkach nie podaje się informacji zwrotnej (na pewno nie szczegółowej, np. z liczbą punktów/słów) żeby - w razie gdyby test nie był dobrym miernikiem - nie wprowadzić rodziców w błąd (że np. dziecko rozwija się poniżej normy/w normie, itd.). Ale jestem też ciekawa co powie @gkrajewski :)

**Comment by gkrajewski** [comment]
Widzę, że się spóźniłem trzy miesiące z odpowiedzą na to issue, ale jeszcze spróbuję, zwłaszcza że chyba nie ustaliliśmy ostatecznie ostatecznej wersji ;)

"Bardzo dziękujemy za [czas i wysiłek poświęcony na] wypełnienie tego kwestionariusza! Proszę śledzić powiadomienia w apce/nowe informacje w zakładce "Wiedza""

@karolina-m ustalmy to jutro, jeśli nie na spotkaniu z @pikrol, to na naszym projektowym zebraniu po południu. Takie info potrzebujemy chyba w każdym z trzech języków?

**Comment by gkrajewski** [comment]
@pikrol Rozumiem, że taki komunikat (np. ten, który zaproponowałem powyżej) siedzi w jednym z plików z treściami, prawda?

**Comment by pikrol** [comment]
Jeszcze nie taki, ale tak będzie on w pliku z treściami.

pt., 12 lut 2021 o 18:02 gkrajewski <notifications@github.com> napisał(a):
